# This workflow will build the project on pull requests with tests
# Uses:
#   OS: ubuntu-lates
#   JDK: Adopt JDK 8

name: PR Builder

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx4g -Xms1g

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Adopt JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn -T 1C clean install -U -B
